apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cromwell_server_test
    mlplatform.volcengine.com/account-id: "2100000050"
    mlplatform.volcengine.com/flavor-id: ml.g1ie.xlarge
    mlplatform.volcengine.com/task-id: cromwell_server_test
    mlplatform.volcengine.com/task-type: pipeline-cromwell
  name: cromwell_server_test
  namespace: cromwell-xcw
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cromwell_server_test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        mlplatform.volcengine.com/account-id: "2100000050"
        mlplatform.volcengine.com/flavor-id: ml.g1ie.xlarge
        #scheduling.volcano.sh/queue-name: q-20220524111638-s9g7r
        mlplatform.volcengine.com/sidecar: '{
          "name":"goofys-sidecar",
          "image":"cr-cn-guilin-boe.volces.com/ml_platform/cloudfs-pub:ea5898c3f3c9d92de1ea88a7b3dbcb89",
          "command":["/bin/sh","-c","trap \"/entrypoint umount\" EXIT TERM KILL; rm -rf /tmp/lifecycle/done.lock; /entrypoint mount \u0026\u0026 \n
            until [ -f /tmp/lifecycle/done.lock ];\n            do\n              sleep 1s;\n            done;\n            exit 0"],
          "env":[
            {"name":"ENDPOINT","value":"http://tos-s3-cn-boe.volces.com"},
            {"name":"REGION","value":"cn-guilin-boe"},
            {"name":"STORAGES","value":"[{\"Type\":\"Tos\",\"MountPath\":\"/app/cromwell-executions\",\"Bucket\":\"cromwell-test\"}]"},
            {"name":"RUNTIME_ENV","value":"normal"},
            {"name":"CLOUDFS_ROOT_PATH_NAME","value":"mlplatform_cromwell"},
            {"name":"SIDECAR_BIZ_TYPE","value":"custom_task"},
            {"name":"AWS_ACCESS_KEY_ID","value":"AKLTZDJhYmY5ODdhYjg3NGEzNWJiMjhlNTY0NDk4ZjA4MzE"},
            {"name":"AWS_SECRET_ACCESS_KEY","value":"WkRZNFlqZGhPV1U0TldJMU5EVXdNemd5TUdKaE1XUmtabUU0T0RFME1qSQ=="}
          ],
          "resources":{
            "limits":{"cpu":"160m","memory":"4543348019200m"},
            "requests":{"cpu":"160m","memory":"4543348019200m"}
          },
          "volumeMounts":[
            {"name":"lifecycle","mountPath":"/tmp/lifecycle/"},
            {"name":"goofys-sidecar-0","mountPath":"/app/cromwell-executions","mountPropagation":"Bidirectional"}
          ],
          "lifecycle":{
            "postStart":{"exec":{"command":["/entrypoint","wait"]}}
          },
          "imagePullPolicy":"Always",
          "securityContext":{"capabilities":{"add":["SYS_ADMIN"]},"privileged":true}
        }'
      labels:
        app: cromwell_server_test
        inference.mlplatform.volcengine.com/account-id: "2100000050"
        mlplatform.volcengine.com/account-id: "2100000050"
        mlplatform.volcengine.com/flavor-id: ml.g1ie.xlarge
        mlplatform.volcengine.com/task-id: s-20220525111658-test4
        mlplatform.volcengine.com/task-type: pipeline-cromwell
    spec:
      containers:
        - env:
            - name: TOS_ENDPOINT_URL
              value: http://tos-s3-cn-boe.volces.com
            - name: TOS_REGION
              value: cn-guilin-boe
            - name: SERVICE_REGION
              value: cn-guilin-boe
            - name: VOLC_ML_PLATFORM_ENV
              value: BOE
            - name: VOLC_AK
              value: AKLTZDJhYmY5ODdhYjg3NGEzNWJiMjhlNTY0NDk4ZjA4MzE
            - name: VOLC_SK
              value: WkRZNFlqZGhPV1U0TldJMU5EVXdNemd5TUdKaE1XUmtabUU0T0RFME1qSQ==
            - name: CROMWELL_TOS_BUCKET
              value: cromwell-test
            - name: CROMWELL_TOS_PREFIX
              value: ""
            - name: CROMWELL_TOS_MOUNT_PATH
              value: /app/cromwell-executions
            - name: CROMWELL_BUILD_CENTAUR_SLICK_PROFILE
              value: slick.jdbc.MySQLProfile$
            - name: CROMWELL_BUILD_CENTAUR_JDBC_DRIVER
              value: com.mysql.cj.jdbc.Driver
            - name: CROMWELL_BUILD_CENTAUR_JDBC_URL
              value: "jdbc:mysql://mysql3c64a08dc375.rds-boe.ivolces.com:3306/cromwell?allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC&useInformationSchema=true"
            - name: CROMWELL_BUILD_CENTAUR_JDBC_USER
              value: cromwell
            - name: CROMWELL_BUILD_CENTAUR_JDBC_PASSWORD
              value: HzVAkwfTbk3
            - name: CROMWELL_BUILD_RESOURCES_DIRECTORY
              value: target/ci/resources
            - name: CROMWELL_BUILD_PAPI_JSON_FILE
              value: target/ci/resources/cromwell-centaur-service-account.json
            - name: CROMWELL_BUILD_CENTAUR_READ_LINES_LIMIT
              value: "128000"
          image: cr-cn-guilin-boe.volces.com/machinelearning/pipeline:cromwell-78-volc-boe-v0.3 # cr-cn-guilin-boe.ivolces.com/ml_platform/tfserving:tf-cuda11.0
          imagePullPolicy: Always
          name: s-20220525111658-test4
          #command: ['sleep', '3600']
          command: ["/bin/zsh", "-c", "\"cd /app && sh cromwell_server_start.sh\""]
          #args: ["cd /app && sh cromwell_server_start.sh"]
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
      terminationGracePeriodSeconds: 30